apiVersion: v1
kind: Service
metadata:
  name: {{ include "simple-webapp.fullname" . }}-frontend
  namespace: {{ .Values.namespace.name }}
  labels:
{{ include "simple-webapp.labels" . | nindent 4 }}
    component: frontend
spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: frontend
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
  type: {{ .Values.frontend.service.type }}
