apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "simple-webapp.fullname" . }}-mongodb
  namespace: {{ .Values.namespace.name }}
  labels:
{{ include "simple-webapp.labels" . | nindent 4 }}
    component: mongodb
spec:
  replicas: {{ .Values.mongodb.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      component: mongodb
  template:
    metadata:
      labels:
{{ include "simple-webapp.labels" . | nindent 8 }}
        component: mongodb
    spec:
      containers:
        - name: mongodb
          image: {{ .Values.mongodb.image }}
          ports:
            - containerPort: {{ .Values.mongodb.port }}
          env:
            - name: MONGO_INITDB_DATABASE
              value: "{{ .Values.mongodb.database }}"
          volumeMounts:
            - name: mongodb-storage
              mountPath: /data/db
      volumes:
        - name: mongodb-storage
          persistentVolumeClaim:
            claimName: {{ include "simple-webapp.fullname" . }}-mongodb-pvc
