apiVersion: v1
kind: Service
metadata:
  name: {{ include "simple-webapp.fullname" . }}-mongodb
  namespace: {{ .Values.namespace.name }}
  labels:
{{ include "simple-webapp.labels" . | nindent 4 }}
    component: mongodb
spec:
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: mongodb
  ports:
    - port: {{ .Values.mongodb.port }}
      targetPort: {{ .Values.mongodb.port }}
  type: ClusterIP
