apiVersion: v2  #format version of the Helm chart, not the Kubernetes API version
name: todo-app
description: Helm chart for the todo application
type: application
version: 0.1.0   #version of the Helm chart itself
appVersion: "1.0.0"
