apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: {{ .Release.Namespace  }}
  labels:
{{ include "mongodb.labels" . | nindent 4 }}
    component: mongodb
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      component: mongodb
  template:
    metadata:
      labels:
{{ include "mongodb.labels" . | nindent 8 }}
        component: mongodb
    spec:
      containers:
        - name: mongodb
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.port }}
          env:
            - name: MONGO_INITDB_DATABASE
              value: "{{ .Values.database}}"
          volumeMounts:
            - name: mongodb-storage
              mountPath: /data/db
      volumes:
        - name: mongodb-storage
          persistentVolumeClaim:
            claimName: mongodb-pvc
