apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: mongodb-pvc
  namespace: webapp

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: gp3-storage

  resources:
    requests:
      storage: 5Gi